# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
State.destroy_all
Produce.destroy_all
Harvest.destroy_all

puts "Destroying all"
puts "\n"
puts "Creating States, Harvests, and Produce"


#############   All of the 50 states ############
al = State.create!(name: "Alabama")
ak = State.create!(name: "Alaska")
ar = State.create!(name: "Arkansas")
az = State.create!(name: "Arizona")
ca = State.create!(name: "California")
co = State.create!(name: "Colorado")
ct = State.create!(name: "Connecticut")
de = State.create!(name: "Delaware")
fl = State.create!(name: "Florida")
ga = State.create!(name: "Georgia")
hi = State.create!(name: "Hawaii")
ida = State.create!(name: "Idaho")
il = State.create!(name: "Illinois")
ind = State.create!(name: "Indiana")
ia = State.create!(name: "Iowa")
ks = State.create!(name: "Kansas")
ky = State.create!(name: "Kentucky")
la = State.create!(name: "Louisana")
me = State.create!(name: "Maine")
md = State.create!(name: "Maryland")
ma = State.create!(name: "Massachusetts")
mi = State.create!(name: "Michigan")
mn = State.create!(name: "Minnesota")
ms = State.create!(name: "Mississippi")
mo = State.create!(name: "Missouri")
mt = State.create!(name: "Montana")
ne = State.create!(name: "Nebraska")
nv = State.create!(name: "Nevada")
nh = State.create!(name: "New Hampshire")
nj = State.create!(name: "New Jersey")
nm = State.create!(name: "New Mexico")
ny = State.create!(name: "New York")
nc = State.create!(name: "North Carolina")
nd = State.create!(name: "North Dakota")
oh = State.create!(name: "Ohio")
ok = State.create!(name: "Oklahoma")
ore = State.create!(name: "Oregon")
pa = State.create!(name: "Pennsylvania")
ri = State.create!(name: "Rhode Island")
sc = State.create!(name: "South Carolina")
sd = State.create!(name: "South Dakota")
tn = State.create!(name: "Tennessee")
tx = State.create!(name: "Texas")
ut = State.create!(name: "Utah")
vt = State.create!(name: "Vermont")
va = State.create!(name: "Virginia")
wa = State.create!(name: "Washington")
wv = State.create!(name: "West Virginia")
wi = State.create!(name: "Wisconsin")
wy = State.create!(name: "Wyoming")


apple = Produce.create!(name: "Apple", description: "Juicy and crisp", image: "https://images.unsplash.com/photo-1576179635662-9d1983e97e1e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1868&q=80")
orange = Produce.create!(name: "Orange", description: "Zesty and juicy", image: "https://images.unsplash.com/photo-1597714026720-8f74c62310ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80")
peach = Produce.create!(name: "Peach", description: "Soft and Juicy", image: "https://images.unsplash.com/photo-1565769583756-fe3ffffcae49?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=668&q=80")
blueberry = Produce.create!(name: "Blueberry", description: "blue", image: "https://images.unsplash.com/photo-1566400628146-ae8f27849e90?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80")
spinach = Produce.create!(name: "Spinach", description: "green and healthy", image: "https://images.unsplash.com/photo-1565489348099-73ff648c76ab?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80")
tomato = Produce.create!(name: "Tomato", description: "red and delicious", image: "https://images.unsplash.com/photo-1536500576323-b9a2af3a6c61?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80")

ramps = Produce.create!(name: "Ramps", description: "happy combination of garlic and onion", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQG98fAXh08vWrd28ox2uLhrkzqzgYl4kuLH9zxWL5Q64B5uCyO0HlbgXacX-KsgW4AtJI&usqp=CAU")
broccoli = Produce.create!(name: "Broccoli", description: "little trees", image: "https://images.unsplash.com/photo-1617122823297-5d390e6074b3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=664&q=80")
garlic_scapes = Produce.create!(name: "Garlic Scapes", description: "short season", image: "https://wpr-public.s3.amazonaws.com/wprorg/styles/facebook/s3/s3fs-public/wpr/segments/2016/05/3705195208_4973e8cbff_o.jpg?itok=-UORCriW")
butternut_squash = Produce.create!(name: "Butternut Squash", description: "makes great soup", image: "https://davidsgiantvegetables.com/wp-content/uploads/2020/10/Butternut-Squash-Growing-e1604159264840.jpg")
watermelon = Produce.create!(name: "Watermelon", description: "huge and juicy", image: "https://edge.bonnieplants.com/www/tiny/uploads/20200810204146/BONNIE_watermelon_iStock-181067852-1800px.jpg")
morels = Produce.create!(name: "Morels", description: "fungi", image: "https://y6auj24xr4y3qq95tz7io6uu-wpengine.netdna-ssl.com/wp-content/uploads/2017/05/32999977933_4b2dd846a5_o-1400x788.jpg")


### Apple's Harvest Cards
ny_apple = Harvest.create!(state: ny, produce: apple, months: ["August", "September", "October"] )
or_apple = Harvest.create!(state: ore, produce: apple, months: [ "September", "October"])
mi_apple = Harvest.create!(state: mi, produce: apple, months: ["August", "September", "October"])
pa_apple = Harvest.create!(state: pa, produce: apple, months: ["July", "August", "September", "October"])
ca_apple = Harvest.create!(state: ca, produce: apple, months: ["July", "August", "September", "October", "November"])
nc_apple = Harvest.create!(state: nc, produce: apple, months: ["August", "September", "October", "November"])
oh_apple = Harvest.create!(state: oh, produce: apple, months: ["July", "August", "September", "October", "November"])
id_apple = Harvest.create!(state: ida, produce: apple, months: ["July", "August", "September"])



##Orange's Harvest
ca_orange = Harvest.create!(state: ca, produce: orange, months: ["January", "February", "March", "April", "May", "June", "December"])
fl_orange = Harvest.create!(state: fl, produce: orange, months: ["January", "September", "October", "November"])
tx_orange = Harvest.create!(state: tx, produce: orange, months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])
az_orange = Harvest.create!(state: az, produce: orange, months: ["January", "February", "March", "April", "November", "December"])
ny_Squash = Harvest.create!(state: ny, produce: butternut_squash, months: ["October", "November", "December"] )


fl_peaches = Harvest.create!(state: fl, produce: peach, months: ["October", "November"])   

## ramps
me_ramp = Harvest.create!(state: me, produce: ramps, months: ["May"])
nh_ramp = Harvest.create!(state: nh, produce: ramps, months: ["May"])
vt_ramp = Harvest.create!(state: vt, produce: ramps, months: ["May"])
ny_ramp = Harvest.create!(state: ny, produce: ramps, months: ["May"])
oh_ramp = Harvest.create!(state: oh, produce: ramps, months: ["May"])
ky_ramp = Harvest.create!(state: ky, produce: ramps, months: ["May"])
pa_ramp = Harvest.create!(state: pa, produce: ramps, months: ["May"])
va_ramp = Harvest.create!(state: va, produce: ramps, months: ["May"])
md_ramp = Harvest.create!(state: md, produce: ramps, months: ["May"])
ma_ramp = Harvest.create!(state: ma, produce: ramps, months: ["May"])
mn_ramp = Harvest.create!(state: mn, produce: ramps, months: ["May"])
mi_ramp = Harvest.create!(state: mi, produce: ramps, months: ["May"])
wi_ramp = Harvest.create!(state: wi, produce: ramps, months: ["May"])
ri_ramp = Harvest.create!(state: ri, produce: ramps, months: ["May"])
il_ramp = Harvest.create!(state: il, produce: ramps, months: ["May"])
mo_ramp = Harvest.create!(state: mo, produce: ramps, months: ["May"])
ga_ramp = Harvest.create!(state: ga, produce: ramps, months: ["May"])


## brocoli
ca_broccoli = Harvest.create!(state: ca, produce: broccoli, months: ["January", "February", "March", "April","May", "June", "July", "August", "September", "October", "November", "December"])
az_broccoli = Harvest.create!(state: az, produce: broccoli, months: ["May"])
tx_broccoli = Harvest.create!(state: tx, produce: broccoli, months: ["October", "January"])
ore_broccoli = Harvest.create!(state: ore, produce: broccoli, months: ["April", "May", "June", "July"])
vt_broccoli = Harvest.create!(state: vt, produce: broccoli, months: ["June", "July"])
nh_broccoli = Harvest.create!(state: nh, produce: broccoli, months: ["June", "July"])
ma_broccoli = Harvest.create!(state: ma, produce: broccoli, months: ["April", "May", "June", "July"])
ny_broccoli = Harvest.create!(state: ny, produce: broccoli, months: ["April", "May", "June", "July"])
pa_broccoli = Harvest.create!(state: pa, produce: broccoli, months: ["April", "May"])

## garlic_scapes
al_garlic_scape = Harvest.create!(state: al, produce: garlic_scapes, months: ["May", "June", "July"])
ak_garlic_scape = Harvest.create!(state: ak, produce: garlic_scapes, months: ["May", "June", "July"])
az_garlic_scape = Harvest.create!(state: az, produce: garlic_scapes, months: ["May", "June", "July"])
ca_garlic_scape = Harvest.create!(state: ca, produce: garlic_scapes, months: ["January", "February", "March", "April","May", "June", "July", "August", "September", "October", "November", "December"])
co_garlic_scape = Harvest.create!(state: co, produce: garlic_scapes, months: ["May", "June", "July"])
ct_garlic_scape = Harvest.create!(state: ct, produce: garlic_scapes, months: ["May", "June", "July"])
de_garlic_scape = Harvest.create!(state: de, produce: garlic_scapes, months: ["May", "June", "July"])
fl_garlic_scape = Harvest.create!(state: fl, produce: garlic_scapes, months: ["May", "June", "July"])
ga_garlic_scape = Harvest.create!(state: ga, produce: garlic_scapes, months: ["May", "June", "July"])
ida_garlic_scape = Harvest.create!(state: ida, produce: garlic_scapes, months: ["May", "June", "July"])
il_garlic_scape = Harvest.create!(state: il, produce: garlic_scapes, months: ["May", "June", "July"])
ind_garlic_scape = Harvest.create!(state: ind, produce: garlic_scapes, months: ["May", "June", "July"])
ia_garlic_scape = Harvest.create!(state: ia, produce: garlic_scapes, months: ["May", "June", "July"])
ks_garlic_scape = Harvest.create!(state: ks, produce: garlic_scapes, months: ["May", "June", "July"])
ky_garlic_scape = Harvest.create!(state: ky, produce: garlic_scapes, months: ["May", "June", "July"])
la_garlic_scape = Harvest.create!(state: la, produce: garlic_scapes, months: ["May", "June", "July"])
me_garlic_scape = Harvest.create!(state: me, produce: garlic_scapes, months: ["May", "June", "July"])
md_garlic_scape = Harvest.create!(state: md, produce: garlic_scapes, months: ["May", "June", "July"])
ma_garlic_scape = Harvest.create!(state: ma, produce: garlic_scapes, months: ["May", "June", "July"])
mi_garlic_scape = Harvest.create!(state: mi, produce: garlic_scapes, months: ["May", "June", "July"])
mn_garlic_scape = Harvest.create!(state: mn, produce: garlic_scapes, months: ["May", "June", "July"])
ms_garlic_scape = Harvest.create!(state: ms, produce: garlic_scapes, months: ["May", "June", "July"])
mo_garlic_scape = Harvest.create!(state: mo, produce: garlic_scapes, months: ["May", "June", "July"])
mt_garlic_scape = Harvest.create!(state: mt, produce: garlic_scapes, months: ["May", "June", "July"])
ne_garlic_scape = Harvest.create!(state: ne, produce: garlic_scapes, months: ["May", "June", "July"])
nv_garlic_scape = Harvest.create!(state: nv, produce: garlic_scapes, months: ["May", "June", "July"])
nh_garlic_scape = Harvest.create!(state: nh, produce: garlic_scapes, months: ["May", "June", "July"])
nj_garlic_scape = Harvest.create!(state: nj, produce: garlic_scapes, months: ["May", "June", "July"])
nm_garlic_scape = Harvest.create!(state: nm, produce: garlic_scapes, months: ["May", "June", "July"])
ny_garlic_scape = Harvest.create!(state: ny, produce: garlic_scapes, months: ["May", "June", "July"])
nc_garlic_scape = Harvest.create!(state: nc, produce: garlic_scapes, months: ["May", "June", "July"])
nd_garlic_scape = Harvest.create!(state: nd, produce: garlic_scapes, months: ["May", "June", "July"])
oh_garlic_scape = Harvest.create!(state: oh, produce: garlic_scapes, months: ["May", "June", "July"])
ok_garlic_scape = Harvest.create!(state: ok, produce: garlic_scapes, months: ["May", "June", "July"])
ore_garlic_scape = Harvest.create!(state: ore, produce: garlic_scapes, months: ["May", "June", "July"])
pa_garlic_scape = Harvest.create!(state: pa, produce: garlic_scapes, months: ["May", "June", "July"])
ri_garlic_scape = Harvest.create!(state: ri, produce: garlic_scapes, months: ["May", "June", "July"])
sc_garlic_scape = Harvest.create!(state: sc, produce: garlic_scapes, months: ["May", "June", "July"])
sd_garlic_scape = Harvest.create!(state: sd, produce: garlic_scapes, months: ["May", "June", "July"])
tn_garlic_scape = Harvest.create!(state: tn, produce: garlic_scapes, months: ["May", "June", "July"])
tx_garlic_scape = Harvest.create!(state: tx, produce: garlic_scapes, months: ["May", "June", "July"])
ut_garlic_scape = Harvest.create!(state: ut, produce: garlic_scapes, months: ["May", "June", "July"])
vt_garlic_scape = Harvest.create!(state: vt, produce: garlic_scapes, months: ["May", "June", "July"])
va_garlic_scape = Harvest.create!(state: va, produce: garlic_scapes, months: ["May", "June", "July"])
wa_garlic_scape = Harvest.create!(state: wa, produce: garlic_scapes, months: ["May", "June", "July"])
wv_garlic_scape = Harvest.create!(state: wv, produce: garlic_scapes, months: ["May", "June", "July"])
wi_garlic_scape = Harvest.create!(state: wi, produce: garlic_scapes, months: ["May", "June", "July"])
wy_garlic_scape = Harvest.create!(state: wy, produce: garlic_scapes, months: ["May", "June", "July"])
## butternut_squash
ca_butternut_squash = Harvest.create!(state: ca, produce: butternut_squash, months: ["January", "February", "March", "April","May", "June", "July", "August", "September", "October", "November", "December"])
ny_butternut_squash = Harvest.create!(state: ny, produce: butternut_squash, months: ["July", "August", "September", "October"])
mi_butternut_squash = Harvest.create!(state: mi, produce: butternut_squash, months: ["September", "October", "November"])
## watermelon
ar_watermelon = Harvest.create!(state: ar, produce: watermelon, months: ["August", "September", "October"])
la_watermelon = Harvest.create!(state: la, produce: watermelon, months: ["August", "September", "October"])
fl_watermelon = Harvest.create!(state: fl, produce: watermelon, months: ["June", "July", "August", "September", "October"])
tx_watermelon = Harvest.create!(state: tx, produce: watermelon, months: ["May", "June", "July", "August", "September"])
ut_watermelon = Harvest.create!(state: ut, produce: watermelon, months: ["September", "October"])
## morels
al_morel = Harvest.create!(state: al, produce: morels, months: ["March"])
ar_morel = Harvest.create!(state: ar, produce: morels, months: ["March"])
ga_morel = Harvest.create!(state: ga, produce: morels, months: ["March"])
sc_morel = Harvest.create!(state: sc, produce: morels, months: ["March"])
ky_morel = Harvest.create!(state: ky, produce: morels, months: ["March", "April"])
tn_morel = Harvest.create!(state: tn, produce: morels, months: ["March", "April"])
ok_morel = Harvest.create!(state: ok, produce: morels, months: ["March", "April"])
nc_morel = Harvest.create!(state: nc, produce: morels, months: ["March", "April"])
md_morel = Harvest.create!(state: md, produce: morels, months: ["March", "April"])
va_morel = Harvest.create!(state: va, produce: morels, months: ["March", "April"])
ind_morel = Harvest.create!(state: ind, produce: morels, months: ["March", "April"])
oh_morel = Harvest.create!(state: oh, produce: morels, months: ["March", "April"])
wv_morel = Harvest.create!(state: wv, produce: morels, months: ["March", "April"])
mo_morel = Harvest.create!(state: mo, produce: morels, months: ["March", "April"])
ks_morel = Harvest.create!(state: ks, produce: morels, months: ["March", "April"])
il_morel = Harvest.create!(state: il, produce: morels, months: ["March", "April"])
pa_morel = Harvest.create!(state: pa, produce: morels, months: ["March", "April", "May"])
ny_morel = Harvest.create!(state: ny, produce: morels, months: ["March", "April", "May"])
ma_morel = Harvest.create!(state: ma, produce: morels, months: ["March", "April", "May"])
nh_morel = Harvest.create!(state: nh, produce: morels, months: ["March", "April", "May"])
vt_morel = Harvest.create!(state: vt, produce: morels, months: ["March", "April", "May"])
ri_morel = Harvest.create!(state: ri, produce: morels, months: ["March", "April", "May"])
ct_morel = Harvest.create!(state: ct, produce: morels, months: ["March", "April", "May"])
me_morel = Harvest.create!(state: me, produce: morels, months: ["March", "April", "May"])